// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// row_erase
NumericMatrix row_erase(NumericMatrix x, IntegerVector rowID);
RcppExport SEXP SpTMixture_row_erase(SEXP xSEXP, SEXP rowIDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rowID(rowIDSEXP);
    rcpp_result_gen = Rcpp::wrap(row_erase(x, rowID));
    return rcpp_result_gen;
END_RCPP
}
// getBonds
NumericMatrix getBonds(NumericMatrix Location, double NN, double th);
RcppExport SEXP SpTMixture_getBonds(SEXP LocationSEXP, SEXP NNSEXP, SEXP thSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Location(LocationSEXP);
    Rcpp::traits::input_parameter< double >::type NN(NNSEXP);
    Rcpp::traits::input_parameter< double >::type th(thSEXP);
    rcpp_result_gen = Rcpp::wrap(getBonds(Location, NN, th));
    return rcpp_result_gen;
END_RCPP
}
// selectBonds
NumericMatrix selectBonds(NumericMatrix Bds, NumericVector Cols, NumericVector Betas);
RcppExport SEXP SpTMixture_selectBonds(SEXP BdsSEXP, SEXP ColsSEXP, SEXP BetasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Bds(BdsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Cols(ColsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Betas(BetasSEXP);
    rcpp_result_gen = Rcpp::wrap(selectBonds(Bds, Cols, Betas));
    return rcpp_result_gen;
END_RCPP
}
// setComp
NumericVector setComp(NumericMatrix Bds, double nvert);
RcppExport SEXP SpTMixture_setComp(SEXP BdsSEXP, SEXP nvertSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Bds(BdsSEXP);
    Rcpp::traits::input_parameter< double >::type nvert(nvertSEXP);
    rcpp_result_gen = Rcpp::wrap(setComp(Bds, nvert));
    return rcpp_result_gen;
END_RCPP
}
// getCompStat
NumericMatrix getCompStat(NumericVector Comp, NumericVector CompID, NumericVector Cols);
RcppExport SEXP SpTMixture_getCompStat(SEXP CompSEXP, SEXP CompIDSEXP, SEXP ColsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Comp(CompSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type CompID(CompIDSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Cols(ColsSEXP);
    rcpp_result_gen = Rcpp::wrap(getCompStat(Comp, CompID, Cols));
    return rcpp_result_gen;
END_RCPP
}
// flipComp
NumericVector flipComp(NumericVector CompID, NumericVector CompIDList, double ncolor);
RcppExport SEXP SpTMixture_flipComp(SEXP CompIDSEXP, SEXP CompIDListSEXP, SEXP ncolorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type CompID(CompIDSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type CompIDList(CompIDListSEXP);
    Rcpp::traits::input_parameter< double >::type ncolor(ncolorSEXP);
    rcpp_result_gen = Rcpp::wrap(flipComp(CompID, CompIDList, ncolor));
    return rcpp_result_gen;
END_RCPP
}
// getCanStatF
NumericMatrix getCanStatF(NumericMatrix Bds, NumericVector Cols, double ncolors);
RcppExport SEXP SpTMixture_getCanStatF(SEXP BdsSEXP, SEXP ColsSEXP, SEXP ncolorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Bds(BdsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Cols(ColsSEXP);
    Rcpp::traits::input_parameter< double >::type ncolors(ncolorsSEXP);
    rcpp_result_gen = Rcpp::wrap(getCanStatF(Bds, Cols, ncolors));
    return rcpp_result_gen;
END_RCPP
}
// getCanStat
NumericVector getCanStat(NumericMatrix Bds, NumericVector Cols, double ncolors);
RcppExport SEXP SpTMixture_getCanStat(SEXP BdsSEXP, SEXP ColsSEXP, SEXP ncolorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Bds(BdsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Cols(ColsSEXP);
    Rcpp::traits::input_parameter< double >::type ncolors(ncolorsSEXP);
    rcpp_result_gen = Rcpp::wrap(getCanStat(Bds, Cols, ncolors));
    return rcpp_result_gen;
END_RCPP
}
// loopSW
NumericVector loopSW(NumericMatrix Bds, NumericVector Cols, double ncolors, int Nrun, NumericVector Betas);
RcppExport SEXP SpTMixture_loopSW(SEXP BdsSEXP, SEXP ColsSEXP, SEXP ncolorsSEXP, SEXP NrunSEXP, SEXP BetasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Bds(BdsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Cols(ColsSEXP);
    Rcpp::traits::input_parameter< double >::type ncolors(ncolorsSEXP);
    Rcpp::traits::input_parameter< int >::type Nrun(NrunSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Betas(BetasSEXP);
    rcpp_result_gen = Rcpp::wrap(loopSW(Bds, Cols, ncolors, Nrun, Betas));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"SpTMixture_row_erase", (DL_FUNC) &SpTMixture_row_erase, 2},
    {"SpTMixture_getBonds", (DL_FUNC) &SpTMixture_getBonds, 3},
    {"SpTMixture_selectBonds", (DL_FUNC) &SpTMixture_selectBonds, 3},
    {"SpTMixture_setComp", (DL_FUNC) &SpTMixture_setComp, 2},
    {"SpTMixture_getCompStat", (DL_FUNC) &SpTMixture_getCompStat, 3},
    {"SpTMixture_flipComp", (DL_FUNC) &SpTMixture_flipComp, 3},
    {"SpTMixture_getCanStatF", (DL_FUNC) &SpTMixture_getCanStatF, 3},
    {"SpTMixture_getCanStat", (DL_FUNC) &SpTMixture_getCanStat, 3},
    {"SpTMixture_loopSW", (DL_FUNC) &SpTMixture_loopSW, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpTMixture(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
